music = {
    "radiohead" : "https://youtu.be/ZVgHPSyEIqk?si=UhHG5nfutjrH0Kf5",
    "cigarettes" : "https://youtu.be/opeETnB8m8w?si=Z4Gv_9diSgQMEp3e",
    "sunset" : "https://youtu.be/5-rbSNzU_b8?si=tUM0rUDO4gMmullz",

    "shape_of_you" : "https://youtu.be/JGwWNGJdvx8",
    "blinding_lights" : "https://youtu.be/4NRXx6U8ABQ",
    "someone_like_you" : "https://youtu.be/hLQl3WQQoQ0",
    "believer" : "https://youtu.be/7wtfhZwyrcc",
    "perfect" : "https://youtu.be/2Vv-BfVoq4g",
    "bad_guy" : "https://youtu.be/DyDfgMOUjCI",
    "see_you_again" : "https://youtu.be/RgKAFK5djSk",
    "faded" : "https://youtu.be/60ItHLz5WEA",
    "let_her_go" : "https://youtu.be/RBumgq5yVrA",
    "rockstar" : "https://youtu.be/UceaB4D0jpo",

    "counting_stars" : "https://youtu.be/hT_nvWreIhg",
    "closer" : "https://youtu.be/PT2_F-1esPk",
    "havana" : "https://youtu.be/HCjNJDNzw8Y",
    "lean_on" : "https://youtu.be/YqeW9_5kURI",
    "cheap_thrills" : "https://youtu.be/nYh-n7EOtMA",
    "stay" : "https://youtu.be/kTJczUoc26U",
    "industry_baby" : "https://youtu.be/UTHLKHL_whs",
    "despacito" : "https://youtu.be/kJQP7kiw5Fk",
    "dance_monkey" : "https://youtu.be/q0hyYWKXF0Q",
    "memories" : "https://youtu.be/SlPhMPnQ58k",

    "thunder" : "https://youtu.be/fKopy74weus",
    "wolves" : "https://youtu.be/cH4E_t3m3xM",
    "senorita" : "https://youtu.be/Pkh8UtuejGw",
    "watermelon_sugar" : "https://youtu.be/E07s5ZYygMg",
    "peaches" : "https://youtu.be/tQ0yjYUFKAE",
    "montero" : "https://youtu.be/6swmTBVI83k",
    "old_town_road" : "https://youtu.be/r7qovpFAGrQ",
    "god_plan" : "https://youtu.be/xpVfcZ0ZcFM",
    "one_dance" : "https://youtu.be/iAbnEUA0wpA",
    "sorry" : "https://youtu.be/fRh_vgS2dFE",

    "thinking_out_loud" : "https://youtu.be/lp-EO5I60KA",
    "hello" : "https://youtu.be/YQHsXMglC9A",
    "rolling_in_the_deep" : "https://youtu.be/rYEDA3JcQqw",
    "shake_it_off" : "https://youtu.be/nfWlot6h_JM",
    "blank_space" : "https://youtu.be/e-ORhEE9VVg",
    "dark_horse" : "https://youtu.be/0KSOMA3QBU0",
    "roar" : "https://youtu.be/CevxZvSJLk8",
    "firework" : "https://youtu.be/QGJuMBdaqIw",
    "uptown_funk" : "https://youtu.be/OPf0YbXqDm0",
    "happy" : "https://youtu.be/ZbZSe6N_BXs",

    "take_on_me" : "https://youtu.be/djV11Xbc914",
    "bohemian_rhapsody" : "https://youtu.be/fJ9rUzIMcZQ",
    "smells_like_teen_spirit" : "https://youtu.be/hTWKbfoikeg",
    "billie_jean" : "https://youtu.be/Zi_XLOBDo_Y",
    "thriller" : "https://youtu.be/sOnqjkJTMaA",
    "hotel_california" : "https://youtu.be/EqPtz5qN7HM",
    "stairway_to_heaven" : "https://youtu.be/QkF3oxziUI4",
    "sweet_child_o_mine" : "https://youtu.be/1w7OgIMMRc4",
    "wonderwall" : "https://youtu.be/bx1Bh8ZvH84",
    "fix_you" : "https://youtu.be/k4V3Mo61fJM"
}